env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-console": "off",
  "import/prefer-default-export": "off",
  'indent': 'off',
  "import/extensions" : "off"
}
